<?php

namespace MathBundle\Repository;

/**
 * OperateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperateurRepository extends \Doctrine\ORM\EntityRepository
{
}
